### ISSUE TITLE
Missing README and LICENSE

### ISSUE THREAD

**Issue by DeathCamel58** [peey/test#5]
Please initialize your repository with a README.md and LICENSE.md file

**After** you do that, feel free to mark this as closed!

It seems like you're learning to use GitHub, so I'm just raising this issue to help push you along.

All the best,
Dylan C

**Comment by DeathCamel58** [comment]
This is honestly getting a bit confusing as to the purpose of this repo. You clearly know how to use GH from your profile page.
Anyways, happy holidays!

**Comment by peey** [comment]
Haha. Sorry to confuse you, random lurker. Is there some website which lets people find new people on GitHub who may need assistance?

Anyways, I made this to just test out new GitHub features (projects) and some apps which integrate with GitHub.
